# Spring properties
spring:
  application:
    name: empleados-web-service  # Identify this application
# ViewResolver
  mvc:
     view:
       prefix: /jsp/
       suffix: .jsp


# HTTP Server
server:
  port: 3333   # HTTP (Tomcat) port

# Config propia
app:
  serviceAlias: empleados-service