# Spring properties
spring:
  application:
    name: empleados-web-service  # Identify this application
  freemarker:
    enabled: false     # Ignore Eureka dashboard FreeMarker templates (¿hace falta?)
# ViewResolver
  mvc:
     view:
       prefix: /jsp/
       suffix: .jsp

# Discovery Server Access
#  1. Define URL of registration server (defaultZone)
#  2. Reduce lease-renewal time so processes register more quickly
eureka:
  instance:
     leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 3333   # HTTP (Tomcat) port
  
app:
  serviceUrl: http://localhost:5555/empleados/
  serviceAlias: empleados-service
